# Generated by Django 4.2.2 on 2023-06-20 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('page', '0001_initial'), ('page', '0002_alter_page_options_element'), ('page', '0003_element_background_image_element_hero_image_and_more'), ('page', '0004_remove_element_background_image_and_more'), ('page', '0005_element_anchor_element_title_and_more'), ('page', '0006_element_order_alter_element_background_image_and_more'), ('page', '0007_element_full_width'), ('page', '0008_remove_element_full_width_element_width'), ('page', '0009_remove_element_width_element_template'), ('page', '0010_alter_element_template'), ('page', '0011_alter_element_template'), ('page', '0012_alter_element_template'), ('page', '0013_remove_element_hero_image_element_hero_image'), ('page', '0014_remove_element_template_element_content_template_and_more'), ('page', '0015_alter_element_hero_image'), ('page', '0016_alter_element_hero_template'), ('page', '0017_alter_element_content_template_and_more'), ('page', '0018_alter_element_content_template'), ('page', '0019_alter_element_hero_template'), ('page', '0020_alter_element_content_template'), ('page', '0021_remove_element_background_image_and_more')]

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_in_menu', models.BooleanField(default=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['site', 'date_created'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Deleted'), (1, 'Revoked'), (2, 'Need Rework'), (3, 'Draft'), (4, 'In Review'), (5, 'Published')])),
                ('content', models.TextField(blank=True, help_text='HTML or Markdown Supported')),
                ('format', models.IntegerField(choices=[(0, 'Plain Text'), (1, 'Markdown'), (2, 'Html'), (3, 'Image')])),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('page', models.ManyToManyField(to='page.page')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('anchor', models.CharField(blank=True, max_length=64)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=1)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hero_image_for', to='page.image')),
                ('content_template', models.TextField(choices=[('one-col', 'One Column Text'), ('two-col', 'Two Column Text'), ('three-col', 'Three Column Text')], default='one_col')),
                ('hero_template', models.TextField(choices=[('hero-none', 'No Hero'), ('hero-left', 'Hero Left'), ('hero-right', 'Hero Right'), ('hero-solo', 'Hero Solo')], default='hero-left')),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='background_image_for', to='page.image')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
